name: Scraper Run

on:
  push:
    branches: ["master", "feature/*"]
  schedule:
    - cron: "0 */6 * * *" # Run every 6 hours

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          playwright install chromium

      - name: Create data directory
        run: |
          mkdir -p data debug

      - name: Run scraper
        run: |
          python src/scraper.py

      - name: Configure Git and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f data/ debug/  # Force add data directory even though it's in .gitignore
          git diff --staged --quiet || (git commit -m "data: update prison census data [skip ci]" && git push)
